name: Create and publish Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  # Run manually
  workflow_dispatch:
  # Run whenever python code or the Dockerfile changes
  push:
    paths:
      - '**.py'
      - '**.ipynb'
      - 'Dockerfile'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: reliable-ai/fairml-multiverse

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages.
      # Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # This step uses docker/metadata-action
      # to extract tags and labels that will be applied to the specified image.
      # The `id` "meta" allows the output of this step to be referenced in a subsequent step.
      # The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # commit hash
            type=sha
            # semver based on tag (if present), e.g. v0.1.2
            # output 0.1.2
            type=semver,pattern={{version}}
            # output 0.1
            type=semver,pattern={{major}}.{{minor}}
            # disabled if major zero
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            # Support for branch or PR names (currently not enabled)
            type=ref,event=branch
            type=ref,event=pr
            # Always set the dev tag
            type=raw,value=dev

      # Build and push the actual Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Test docker image
      - name: Test Docker image
        run: docker run --rm ghcr.io/reliable-ai/fairml-multiverse pipenv run python -m unittest
